//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.appstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMaster
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public string logtext { get; set; }
    }
}
